name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm tsc --noEmit

      - name: Lint
        run: pnpm lint

      - name: Check formatting
        run: pnpm prettier:check

      - name: Build
        run: pnpm build

      - name: Audit dependencies
        run: pnpm audit --audit-level=high

      - name: Check bundle size
        run: pnpm size-limit

      - name: Run tests
        run: pnpm test
        if: hashFiles('**/*.test.*') != ''
